{% set version = "12.3.2" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart-static 12.3.101
    - cuda-nvrtc-static 12.3.107
    - libcublas-static 12.3.4.1   # [linux]
    - libcufft-static 11.0.12.1     # [linux]
    - libcufile-static 1.8.1.2     # [linux64 or aarch64]
    - libcurand-static 10.3.4.107    # [linux]
    - libcusolver-static 11.5.4.101  # [linux]
    - libcusparse-static 12.2.0.103  # [linux]
    - libnpp-static 12.2.3.2       # [linux]
    - libnvjitlink-static 12.3.101
    - libnvjpeg-static 12.3.0.81    # [linux]

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
