{% set version = "12.4.0" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart-static 12.4.99
    - cuda-nvrtc-static 12.4.99
    - libcublas-static 12.4.2.65      # [linux]
    - libcufft-static 11.2.0.44      # [linux]
    - libcufile-static 1.9.0.20       # [linux64 or aarch64]
    - libcurand-static 10.3.5.119    # [linux]
    - libcusolver-static 11.6.0.99  # [linux]
    - libcusparse-static 12.3.0.142  # [linux]
    - libnpp-static 12.2.5.2         # [linux]
    - libnvfatbin-static 12.4.99
    - libnvjitlink-static 12.4.99
    - libnvjpeg-static 12.3.1.89     # [linux]

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
