{% set version = "12.2.2" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart-static 12.2.140
    - cuda-nvrtc-static 12.2.140
    - libcublas-static 12.2.5.6   # [linux]
    - libcufft-static 11.0.8.103     # [linux]
    - libcufile-static 1.7.2.10     # [linux64]
    - libcurand-static 10.3.3.141    # [linux]
    - libcusolver-static 11.5.2.141  # [linux]
    - libcusparse-static 12.1.2.141  # [linux]
    - libnpp-static 12.2.1.4       # [linux]
    - libnvjitlink-static 12.2.140
    - libnvjpeg-static 12.2.2.4    # [linux]

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
