{% set version = "13.1.1" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart-static 13.1.80
    - cuda-culibos-static 13.1.115    # [linux]
    - cuda-nvrtc-static 13.1.115
    - libcublas-static 13.2.1.1      # [linux]
    - libcufft-static 12.1.0.78      # [linux]
    - libcufile-static 1.16.1.26       # [linux]
    - libcurand-static 10.4.1.81    # [linux]
    - libcusolver-static 12.0.9.81  # [linux]
    - libcusparse-static 12.7.3.1  # [linux]
    - libnpp-static 13.0.3.3         # [linux]
    - libnvfatbin-static 13.1.115
    - libnvjitlink-static 13.1.115
    - libnvjpeg-static 13.0.3.75     # [linux]

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html
  dev_url: https://docs.nvidia.com/cuda/index.html

extra:
  skip-lints:
    - license_file_overspecified
  recipe-maintainers:
    - conda-forge/cuda
